networks:
  schedule-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: schedule-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s 
    networks:
      - schedule-network

  backend:
    build: .
    container_name: schedule-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5000:5000"
    networks:
      - schedule-network

volumes:
  postgres_data:
